version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1


jobs:
  build: 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - run:
          name: install the frontend dependencies
          command: npm run front
      - run:
          name: install the backend dependencies
          command: npm run back
      - run:
          name: build the frontend project
          command: npm run front_Build
      - run:
          name: build the backend project
          command: npm run back_Build
      - run:
          name: backend deploy
          command: npm run back_Deploy
      - run:
          name: frontend deploy
          command: npm run front_Deploy

workflows:
  Udagram:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
