version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1
  browser: circleci/browser-tools@1.2.4
   
jobs:
  Build-Deploy: 
    docker:
      - image: cimg/base:stable
    steps: 
      - checkout
      - browser/install-chrome
      - node/install:
          install-yarn: true
          node-version: "16.14"
      - aws-cli/setup
      - eb/setup
      - run:
         name: Frontend Install
         command: npm run frontend:install
      - run:
         name: Frontend Build
         command: npm run frontend:build
      - run:
         name: Frontend Deploy
         command: npm run frontend:deploy
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Change Main Entry Point
          command: |
            npm run backend:change-main
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Installing AWS Elasticbeanstalk
          command: |
            npm run backend:aws-eb
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy

  
workflows:
  deployment:
    jobs:
    - Build-Deploy:
         filters:
            branches:
              only: main